/**
 * MISSION TEMPLATES
 *
 * Predefined orchestrations for common Hunter goals.
 * Each template defines a sequence of touchpoints (steps) that Barry
 * proposes when a user selects a goal.
 *
 * Philosophy: Goal-first, not weapon-first.
 * User picks what they want to achieve, Barry handles the how.
 */

export const MISSION_TEMPLATES = {
  book_meetings: {
    id: 'book_meetings',
    name: 'Book Meetings',
    description: 'Multi-touch sequence designed to get meetings on the calendar',
    icon: '📅',
    defaultName: 'Meeting Mission',
    steps: [
      {
        id: 'step_1',
        weapon: 'email',
        type: 'intro',
        label: 'Intro Email',
        timing: 'Day 1',
        delayDays: 0,
        description: 'Opening value proposition'
      },
      {
        id: 'step_2',
        weapon: 'email',
        type: 'followup',
        label: 'Follow-up Email',
        timing: 'Day 3',
        delayDays: 2,
        description: 'Gentle reminder with additional value'
      },
      {
        id: 'step_3',
        weapon: 'text',
        type: 'nudge',
        label: 'SMS Nudge',
        timing: 'Day 5',
        delayDays: 4,
        description: 'Short, direct text message'
      },
      {
        id: 'step_4',
        weapon: 'phone',
        type: 'task',
        label: 'Call Task',
        timing: 'Day 7',
        delayDays: 6,
        description: 'Reminder to make a phone call'
      },
      {
        id: 'step_5',
        weapon: 'email',
        type: 'breakup',
        label: 'Breakup Email',
        timing: 'Day 10',
        delayDays: 9,
        description: 'Final attempt before moving on'
      }
    ]
  },

  warm_conversations: {
    id: 'warm_conversations',
    name: 'Start Warm Conversations',
    description: 'Light touch sequence to open dialogue without being pushy',
    icon: '💬',
    defaultName: 'Warm Outreach',
    steps: [
      {
        id: 'step_1',
        weapon: 'email',
        type: 'intro',
        label: 'Friendly Intro',
        timing: 'Day 1',
        delayDays: 0,
        description: 'Low-pressure opening message'
      },
      {
        id: 'step_2',
        weapon: 'text',
        type: 'nudge',
        label: 'SMS Check-in',
        timing: 'Day 4',
        delayDays: 3,
        description: 'Casual text to stay top of mind'
      },
      {
        id: 'step_3',
        weapon: 'email',
        type: 'followup',
        label: 'Value Add Email',
        timing: 'Day 7',
        delayDays: 6,
        description: 'Share something helpful, no ask'
      }
    ]
  },

  reengage_stalled: {
    id: 'reengage_stalled',
    name: 'Re-engage Stalled Leads',
    description: 'Win back leads who went dark',
    icon: '🔄',
    defaultName: 'Re-engagement Campaign',
    steps: [
      {
        id: 'step_1',
        weapon: 'email',
        type: 'reengage',
        label: 'Re-engagement Email',
        timing: 'Day 1',
        delayDays: 0,
        description: 'Acknowledge the silence, offer new value'
      },
      {
        id: 'step_2',
        weapon: 'text',
        type: 'nudge',
        label: 'Quick Text',
        timing: 'Day 3',
        delayDays: 2,
        description: 'Brief check-in via SMS'
      },
      {
        id: 'step_3',
        weapon: 'email',
        type: 'breakup',
        label: 'Final Attempt',
        timing: 'Day 7',
        delayDays: 6,
        description: 'Last chance before archiving'
      }
    ]
  }
};

/**
 * Get template by goal ID
 */
export function getTemplateByGoal(goalId) {
  return MISSION_TEMPLATES[goalId] || null;
}

/**
 * Get all available goals (for selection UI)
 */
export function getAllGoals() {
  return Object.values(MISSION_TEMPLATES);
}

/**
 * Create a mission instance from a template
 */
export function createMissionFromTemplate(goalId, missionName, contacts = []) {
  const template = getTemplateByGoal(goalId);
  if (!template) throw new Error(`Template not found for goal: ${goalId}`);

  return {
    name: missionName || template.defaultName,
    goal: goalId,
    goalName: template.name,
    steps: template.steps.map(step => ({
      ...step,
      message: null, // Will be generated by AI
      subject: null, // For email steps
      enabled: true,
      status: 'draft'
    })),
    contacts: contacts.map(contact => ({
      contactId: contact.id,
      name: `${contact.firstName} ${contact.lastName}`,
      email: contact.email || null,
      phone: contact.phone || null,
      currentStepIndex: 0,
      lastTouchDate: null,
      status: 'pending',
      outcomes: []
    })),
    status: 'draft', // draft -> autopilot -> paused -> completed
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    completedAt: null
  };
}
