/**
 * BulkSendExecutor — Scout Campaign bulk send loop + progress UI.
 *
 * Receives the final array of { contact, subject, body } from BulkComposeModal
 * (Step 3) and sends to each contact sequentially through executeSendAction —
 * the unified send pipeline (auth, token refresh, timeline logging, state
 * machine, email_logs). Never calls gmail-send-* functions directly.
 *
 * Loop rules:
 *   - Sequential, with a mandatory 1500ms delay between sends. Do not remove
 *     it — it protects the user's Gmail account from rate limiting/spam flags.
 *   - Per-contact status: pending → sending → sent | opened | failed.
 *   - OPENED (native mail app handoff) is a valid non-failure outcome.
 *   - The loop never aborts early — every contact gets attempted.
 *   - "Retry failed" re-runs the loop for failed contacts only.
 *   - No cancel button during an active send.
 */

import { useState, useEffect, useRef } from 'react';
import {
  Send, CheckCircle2, XCircle, Mail, Clock, Loader, RotateCcw, AlertTriangle, UserPlus,
} from 'lucide-react';
import { collection, addDoc, doc, updateDoc, getDoc, serverTimestamp } from 'firebase/firestore';
import { executeSendAction, CHANNELS, SEND_RESULT } from '../../utils/sendActionResolver';
import { getEffectiveUser } from '../../context/ImpersonationContext';
import { db } from '../../firebase/config';
import { useT } from '../../theme/ThemeContext';

export const SEND_DELAY_MS = 1500; // mandatory inter-send delay — do not remove

const GREEN = '#22c55e';
const RED   = '#ef4444';
const BLUE  = '#3b82f6';
const GRAY  = '#94a3b8';

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

const STATUS_CONFIG = {
  pending: { label: 'Pending',            color: GRAY,  icon: Clock },
  sending: { label: 'Sending…',           color: GRAY,  icon: Loader, spin: true },
  sent:    { label: 'Sent',               color: GREEN, icon: CheckCircle2 },
  opened:  { label: 'Opened in mail app', color: BLUE,  icon: Mail },
  failed:  { label: 'Failed',             color: RED,   icon: XCircle },
};

function getContactName(contact) {
  return contact.name
    || [contact.firstName, contact.lastName].filter(Boolean).join(' ')
    || contact.email
    || 'Unknown';
}

export default function BulkSendExecutor({ payload, T: TProp, onAddMoreContacts, onComplete }) {
  const TContext = useT();
  const T = TProp || TContext;
  // contactId → { status, reason }
  const [statuses, setStatuses] = useState(() =>
    Object.fromEntries((payload || []).map((p) => [p.contact.id, { status: 'pending' }]))
  );
  const [running, setRunning] = useState(false);
  const [complete, setComplete] = useState(false);
  const startedRef = useRef(false); // guards StrictMode double-mount
  const cadenceIdRef = useRef(null); // pre-minted cadence doc id, threaded into each send for open tracking

  const items = payload || [];
  const total = items.length;

  function setContactStatus(contactId, status, reason = null, meta = null) {
    setStatuses((prev) => ({ ...prev, [contactId]: { status, reason, ...meta } }));
  }

  async function sendOne(item) {
    const { contact, subject, body, attachment, cc } = item;
    setContactStatus(contact.id, 'sending');
    try {
      const userId = getEffectiveUser()?.uid;
      const args = { channel: CHANNELS.EMAIL, userId, contact, subject, body };
      if (attachment) args.attachment = attachment;
      if (cc) args.cc = cc;
      // Thread the pre-minted cadence id through so gmail-send-quick can embed
      // the open-tracking pixel. Null when pre-mint failed → send is untracked.
      if (cadenceIdRef.current) args.cadenceId = cadenceIdRef.current;
      const res = await executeSendAction(args);

      const sendMeta = {
        gmailMessageId: res?.gmailMessageId || null,
        gmailThreadId: res?.gmailThreadId || null,
      };
      switch (res?.result) {
        case SEND_RESULT.SENT:
          setContactStatus(contact.id, 'sent', null, sendMeta);
          break;
        case SEND_RESULT.OPENED:
          setContactStatus(contact.id, 'opened', null, sendMeta);
          break;
        case SEND_RESULT.UNAVAILABLE:
          setContactStatus(contact.id, 'failed', 'No email address on file');
          break;
        case SEND_RESULT.FAILED:
          setContactStatus(contact.id, 'failed', res.error || res.reason || 'Send failed');
          break;
        default:
          setContactStatus(contact.id, 'failed', `Unexpected result: ${res?.result || 'none'}`);
      }
    } catch (err) {
      setContactStatus(contact.id, 'failed', err?.message || 'Send failed');
    }
  }

  async function runLoop(toSend) {
    setComplete(false);
    setRunning(true);
    for (let i = 0; i < toSend.length; i++) {
      await sendOne(toSend[i]);
      if (i < toSend.length - 1) await sleep(SEND_DELAY_MS);
    }
    setRunning(false);
    setComplete(true);
    onComplete?.();
  }

  // Resolve the cadence name once (user-provided, else auto-generated by date).
  function resolveCadenceName() {
    const providedName = items[0]?.cadenceName?.trim();
    return providedName || `Cadence - ${new Date().toLocaleDateString('en-US', {
      month: 'short', day: 'numeric', year: 'numeric',
    })}`;
  }

  function buildContactEntry(p) {
    return {
      contactId: p.contact.id,
      name: getContactName(p.contact),
      email: p.contact.email || p.contact.work_email || '',
      status: 'pending',
      reason: null,
      gmailMessageId: null,
      gmailThreadId: null,
    };
  }

  useEffect(() => {
    if (startedRef.current || items.length === 0) return;
    startedRef.current = true;

    (async () => {
      // Pre-mint the cadence doc so its ID exists during the send loop — the
      // open-tracking pixel needs a real cadenceId at send time (the doc is no
      // longer created only at completion). Non-blocking: if this fails, the
      // loop still runs and completion falls back to creating the doc.
      try {
        const userId = getEffectiveUser()?.uid;
        if (userId) {
          const ref = await addDoc(collection(db, 'users', userId, 'cadences'), {
            userId,
            name: resolveCadenceName(),
            status: 'active',
            subject: items[0].subject || '',
            body: items[0].body || '',
            contactCount: items.length,
            contacts: items.map(buildContactEntry),
            sentCount: 0,
            openedCount: 0,
            nativeHandoffCount: 0,
            failedCount: 0,
            createdAt: serverTimestamp(),
          });
          cadenceIdRef.current = ref.id;
        }
      } catch (err) {
        console.warn('[BulkSendExecutor] Failed to pre-create cadence record', err);
      }

      runLoop(items);
    })();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  function handleRetryFailed() {
    const failedItems = items.filter((p) => statuses[p.contact.id]?.status === 'failed');
    if (failedItems.length === 0 || running) return;
    setStatuses((prev) => {
      const next = { ...prev };
      failedItems.forEach((p) => { next[p.contact.id] = { status: 'pending' }; });
      return next;
    });
    runLoop(failedItems);
  }

  const counts = { sent: 0, opened: 0, failed: 0, done: 0 };
  items.forEach((p) => {
    const s = statuses[p.contact.id]?.status;
    if (s === 'sent') counts.sent++;
    if (s === 'opened') counts.opened++;
    if (s === 'failed') counts.failed++;
    if (s === 'sent' || s === 'opened' || s === 'failed') counts.done++;
  });
  const delivered = counts.sent + counts.opened;
  const failedContacts = items.filter((p) => statuses[p.contact.id]?.status === 'failed');

  // ─── Cadence record write ───
  // Fire-and-forget: once the campaign completes, persist a single history
  // record to users/{uid}/cadences for the Cadences dashboard. Additive only —
  // never blocks the UI and never surfaces errors (the send already succeeded).
  const cadenceWrittenRef = useRef(false);
  useEffect(() => {
    if (!complete || items.length === 0 || cadenceWrittenRef.current) return;
    cadenceWrittenRef.current = true;

    (async () => {
      try {
        const userId = getEffectiveUser()?.uid;
        if (!userId) return;

        // Final per-contact send status, keyed by id for merging.
        const finalById = Object.fromEntries(items.map((p) => {
          const entry = statuses[p.contact.id] || {};
          return [p.contact.id, {
            status: entry.status || 'pending',
            reason: entry.reason ?? null,
            // Carry Team B's send-loop-captured ids so the read-merge writes
            // them onto the cadence contact entries.
            gmailMessageId: entry.gmailMessageId ?? null,
            gmailThreadId: entry.gmailThreadId ?? null,
          }];
        }));

        const cadenceId = cadenceIdRef.current;

        if (cadenceId) {
          // Finalize the pre-minted doc. Read-merge the contacts array so fields
          // written concurrently by open tracking (opened / openedAt) or by the
          // send pipeline (e.g. gmailThreadId) survive — only status/reason are
          // overlaid from the send loop.
          const ref = doc(db, 'users', userId, 'cadences', cadenceId);
          let mergedContacts;
          try {
            const snap = await getDoc(ref);
            const existing = snap.exists() && Array.isArray(snap.data().contacts)
              ? snap.data().contacts : [];
            mergedContacts = existing.map((c) => {
              const upd = finalById[c?.contactId];
              return upd ? { ...c, ...upd } : c;
            });
          } catch {
            // Read failed — rebuild from scratch (only concurrent opens are lost).
            mergedContacts = items.map((p) => ({ ...buildContactEntry(p), ...finalById[p.contact.id] }));
          }

          await updateDoc(ref, {
            status: 'completed',
            contacts: mergedContacts,
            sentCount: counts.sent,
            failedCount: counts.failed,
            // openedCount is owned exclusively by track-open (recipient pixel
            // opens) and is intentionally not written here. Native mail-app
            // handoffs (OPENED result, Gmail not connected) count separately.
            nativeHandoffCount: counts.opened,
            completedAt: serverTimestamp(),
          });
        } else {
          // Pre-mint failed — fall back to creating the record at completion.
          await addDoc(collection(db, 'users', userId, 'cadences'), {
            userId,
            name: resolveCadenceName(),
            status: 'completed',
            subject: items[0].subject || '',
            body: items[0].body || '',
            contactCount: items.length,
            contacts: items.map((p) => ({ ...buildContactEntry(p), ...finalById[p.contact.id] })),
            sentCount: counts.sent,
            // No pre-minted cadenceId → no pixel embedded → no recipient opens.
            openedCount: 0,
            nativeHandoffCount: counts.opened,
            failedCount: counts.failed,
            createdAt: serverTimestamp(),
            completedAt: serverTimestamp(),
          });
        }
      } catch (err) {
        console.warn('[BulkSendExecutor] Failed to finalize cadence record', err);
      }
    })();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [complete]);

  if (total === 0) {
    return (
      <div style={{ padding: '30px 20px', textAlign: 'center', fontSize: 13, color: T.textMuted }}>
        No contacts to send to.
      </div>
    );
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
      {/* ─── Header + status message ─── */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
        <div style={{
          width: 36, height: 36, borderRadius: 10, flexShrink: 0,
          background: complete ? `${GREEN}15` : `${BLUE}15`,
          display: 'flex', alignItems: 'center', justifyContent: 'center',
        }}>
          <Send size={16} style={{ color: complete ? GREEN : BLUE }} />
        </div>
        <div>
          <div style={{ fontSize: 14, fontWeight: 700, color: T.text }}>
            {complete
              ? `${delivered} sent, ${counts.failed} failed`
              : `Sending ${counts.done < total ? counts.done + 1 : total} of ${total}…`}
          </div>
          <div style={{ fontSize: 11, color: running ? RED : T.textFaint, fontWeight: running ? 600 : 400 }}>
            {running
              ? 'Sending — do not close this tab'
              : complete && counts.opened > 0
                ? `${counts.sent} via Gmail, ${counts.opened} opened in mail app`
                : complete ? 'Campaign complete' : ''}
          </div>
        </div>
      </div>

      {/* ─── Progress bar ─── */}
      <div>
        <div style={{
          display: 'flex', justifyContent: 'space-between',
          fontSize: 11, color: T.textFaint, marginBottom: 5,
        }}>
          <span>{delivered} of {total} sent</span>
          <span>{Math.round((counts.done / total) * 100)}%</span>
        </div>
        <div style={{ height: 6, borderRadius: 3, background: T.border, overflow: 'hidden' }}>
          <div style={{
            height: '100%', borderRadius: 3, background: GREEN,
            width: `${(counts.done / total) * 100}%`,
            transition: 'width 0.3s ease',
          }} />
        </div>
      </div>

      {/* ─── Per-contact status list ─── */}
      <div style={{
        maxHeight: 300, overflowY: 'auto',
        display: 'flex', flexDirection: 'column', gap: 6,
      }}>
        {items.map((p) => {
          const entry = statuses[p.contact.id] || { status: 'pending' };
          const sc = STATUS_CONFIG[entry.status] || STATUS_CONFIG.pending;
          const StatusIcon = sc.icon;
          return (
            <div
              key={p.contact.id}
              style={{
                display: 'flex', alignItems: 'center', gap: 10,
                padding: '9px 12px', borderRadius: 10,
                border: `1px solid ${entry.status === 'failed' ? `${RED}40` : T.border}`,
                background: entry.status === 'failed' ? `${RED}06` : T.surface,
              }}
            >
              <StatusIcon
                size={15}
                style={{
                  color: sc.color, flexShrink: 0,
                  ...(sc.spin ? { animation: 'spin 1s linear infinite' } : {}),
                }}
              />
              <div style={{ flex: 1, minWidth: 0 }}>
                <div style={{
                  fontSize: 12, fontWeight: 600, color: T.text,
                  overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap',
                }}>
                  {getContactName(p.contact)}
                </div>
                <div style={{
                  fontSize: 10, color: T.textFaint,
                  overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap',
                }}>
                  {p.contact.email || p.contact.work_email || ''}
                </div>
              </div>
              <div style={{ textAlign: 'right', flexShrink: 0 }}>
                <span style={{
                  fontSize: 10, fontWeight: 600, color: sc.color,
                  background: `${sc.color}12`, padding: '3px 8px', borderRadius: 8,
                }}>
                  {sc.label}
                </span>
                {entry.status === 'failed' && entry.reason && (
                  <div style={{ fontSize: 10, color: RED, marginTop: 3, maxWidth: 180 }}>
                    {entry.reason}
                  </div>
                )}
              </div>
            </div>
          );
        })}
      </div>

      {/* ─── Completion summary ─── */}
      {complete && counts.failed > 0 && (
        <div style={{
          padding: '10px 14px', borderRadius: 10,
          background: `${RED}08`, border: `1px solid ${RED}30`,
        }}>
          <div style={{
            display: 'flex', alignItems: 'center', gap: 7,
            fontSize: 12, fontWeight: 600, color: RED, marginBottom: 6,
          }}>
            <AlertTriangle size={13} />
            {counts.failed} contact{counts.failed !== 1 ? 's' : ''} failed
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 3 }}>
            {failedContacts.map((p) => (
              <div key={p.contact.id} style={{ fontSize: 11, color: T.textMuted }}>
                <strong style={{ color: T.text }}>{getContactName(p.contact)}</strong>
                {' — '}{statuses[p.contact.id]?.reason || 'Unknown error'}
              </div>
            ))}
          </div>
          <button
            onClick={handleRetryFailed}
            style={{
              marginTop: 10, padding: '7px 14px', borderRadius: 8,
              border: `1px solid ${RED}`, background: `${RED}12`,
              color: RED, fontSize: 12, fontWeight: 600, cursor: 'pointer',
              display: 'flex', alignItems: 'center', gap: 6,
            }}
          >
            <RotateCcw size={12} />
            Retry failed ({counts.failed})
          </button>
        </div>
      )}

      {/* ─── Add more contacts button (post-campaign) ─── */}
      {complete && !running && onAddMoreContacts && (
        <button
          onClick={onAddMoreContacts}
          style={{
            padding: '9px 16px', borderRadius: 10,
            border: `1px solid ${T.border}`,
            background: T.surface, color: T.text,
            fontSize: 12, fontWeight: 600, cursor: 'pointer',
            display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 6,
          }}
        >
          <UserPlus size={13} />
          Add more contacts to this campaign
        </button>
      )}

      <style>{`
        @keyframes spin {
          from { transform: rotate(0deg); }
          to   { transform: rotate(360deg); }
        }
      `}</style>
    </div>
  );
}
